/* Copyright (c) 2011-2014, EPFL/Blue Brain Project
 *                     Ahmet Bilgili <ahmet.bilgili@epfl.ch>
 *
 * This file is part of Livre <https://github.com/BlueBrain/Livre>
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License version 3.0 as published
 * by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef _RenderView_h_
#define _RenderView_h_

#include <livre/lib/api.h>
#include <livre/lib/types.h>
#include <livre/core/render/View.h>
#include <livre/core/render/Frustum.h>
#include <livre/core/dash/DashRenderNode.h>
#include <livre/lib/configuration/VolumeRendererParameters.h>

namespace livre
{

/**
 * The RenderView class implements the expanded frustum algorithm. Frustum is generated by the classes that
 * derives this class.
 */
class RenderView : public View
{
public:
    LIVRE_API RenderView( ConstDashTreePtr dashTree );
    LIVRE_API ~RenderView();

private:
    LIVRE_API void _onPostRender( const GLWidget& widget,
                                  const FrameInfo& frameInfo ) final;

    struct Impl;
    Impl* _impl;
};

}


#endif // _RenderView_h_
