set(LIVREEQ_HEADERS
  Channel.h
  Client.h
  Config.h
  ConnectionDefinitions.h
  Error.h
  Events/EqEventHandlerFactory.h
  Events/EqEventHandlerFactory.h
  Events/EqEventInfo.h
  Events/Events.h
  Events/Handlers/ChannelPointerHandler.h
  Events/Handlers/KeyboardHandler.h
  FrameData.h
  FrameGrabber.h
  Node.h
  Pipe.h
  Render/EqContext.h
  Render/RayCastRenderer.h
  Settings/CameraSettings.h
  Settings/FrameSettings.h
  Settings/RenderSettings.h
  Settings/VolumeSettings.h
  Window.h
  coTypes.h
  eqTypes.h
  types.h
  )

set(LIVREEQ_SOURCES
  Channel.cpp
  Client.cpp
  Config.cpp
  Error.cpp
  Events/EqEventHandler.cpp
  Events/EqEventHandlerFactory.cpp
  Events/Handlers/ChannelPointerHandler.cpp
  Events/Handlers/KeyboardHandler.cpp
  FrameData.cpp
  FrameGrabber.cpp
  Node.cpp
  Pipe.cpp
  Render/EqContext.cpp
  Render/RayCastRenderer.cpp
  Settings/CameraSettings.cpp
  Settings/FrameSettings.cpp
  Settings/RenderSettings.cpp
  Settings/VolumeSettings.cpp
  Window.cpp
  )
